### PR TITLE
feat(pcr): Add Flow.CPUVendorID()

### PR DESCRIPTION
**Pull request by xaionaro**
Depends on https://github.com/9elements/go-linux-lowlevel-hw/pull/9 to be merged.

### CODE REVIEW

**Review by trynity — APPROVED** [review]

**Comment by trynity** [comment]
There are build errors that need to be addressed, but overall the changes look good.

**Comment by xaionaro** [comment]
@trynity : The build errors are because [the dependency](https://github.com/9elements/go-linux-lowlevel-hw/pull/9) is not merged, yet.

**Review by rihter007 — APPROVED** [review]
lgtm

**Review by zaolin — APPROVED** [review]

**Review by ChriMarMe — APPROVED** [review]

**Comment by xaionaro** [comment]
@zaolin : Could you take a look at https://github.com/9elements/go-linux-lowlevel-hw/pull/9, please? I cannot merge this PR before that PR is merged.

**Comment by xaionaro** [comment]
Now there is another dependency :( -- https://github.com/9elements/go-linux-lowlevel-hw/pull/10

**Comment by xaionaro** [comment]
Splitted to 2 commits for easier review.

**Review by ChriMarMe — APPROVED** [review]

**Pull request merged**
